banner_location:
    default: above-main-container
    type: enum
    choices:
        - above-main-container
        - above-site-header
        - below-site-header
    description: "The plugin outlet location of the banner."


banner_text_color:
    default: "var(--primary)"
    type: string
    description: "The text color of the banner."


banner_background_color:
    default: "var(--tertiary-low)"
    type: string
    description: "The background color of the banner."

