banner_location:
    default: above-main-container
    type: enum
    choices:
        - above-main-container
        - above-site-header
        - below-site-header

banner_text_color:
    default: "var(--primary)"
    type: string

banner_background_color:
    default: "var(--tertiary-low)"
    type: string

anniversaries_text:
    default: "%{count} users are celebrating their anniversaries today!"
    type: string

birthdays_text:
    default: "%{count} users are celebrating their birthdays today!"
    type: string
